#!/bin/bash
echo Content-type: text/plain
echo

cd /home/groups/z/za/zapping/twiki

# Cannot chmod to `whoami`, so here we go.

umask 033

for dir in data pub; do
  echo $dir
  cp -darp $dir $dir.tmp && rm -rf $dir && mv $dir.tmp $dir
done

# Need a+rX for cron'ed backups.
chmod -R a+rX,ug+w,o-w .

echo
echo OK
