/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_zapping (void);
GtkWidget* create_channel_window (void);
GtkWidget* create_zapping_properties (void);
GtkWidget* create_about2 (void);
