/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_EXIT_ITEM (on_exit2_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PROPERTIES_ITEM (on_propiedades1_activate, NULL),
  {
    GNOME_APP_UI_ITEM, N_("P_lugins"),
    NULL,
    on_plugins1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_ATTACH,
    0, 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_TV Channels"),
    NULL,
    on_channels1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_INDEX,
    0, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo vista1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Go _Fullscreen"),
    N_("Use this to go fullscreen. Press ESC to return to Windowed mode"),
    on_go_fullscreen1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_F, GDK_CONTROL_MASK | GDK_MOD1_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Go _Windowed"),
    NULL,
    on_go_windowed1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    GDK_Escape, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo go_zapping1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Channel up"),
    NULL,
    on_channel_up1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_TOP,
    GDK_Page_Up, 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Channel down"),
    NULL,
    on_channel_down1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_BOTTOM,
    GDK_Page_Down, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_ABOUT_ITEM (on_about1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  GNOMEUIINFO_MENU_VIEW_TREE (vista1_menu_uiinfo),
  {
    GNOME_APP_UI_SUBTREE, N_("Go _Zapping"),
    NULL,
    go_zapping1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, 0, NULL
  },
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_zapping (void)
{
  GtkWidget *zapping;
  GtkWidget *dock1;
  GtkWidget *toolbar1;
  GtkWidget *Channels;
  GtkWidget *Channels_menu;
  GtkWidget *Inputs;
  GtkWidget *Inputs_menu;
  GtkWidget *Standards;
  GtkWidget *Standards_menu;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button1;
  GtkWidget *screenshot;
  GtkWidget *tv_screen;

  zapping = gnome_app_new ("Zapping", _("Zapping"));
  gtk_object_set_data (GTK_OBJECT (zapping), "zapping", zapping);

  dock1 = GNOME_APP (zapping)->dock;
  gtk_widget_ref (dock1);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "dock1", dock1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dock1);

  gnome_app_create_menus (GNOME_APP (zapping), menubar1_uiinfo);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "file1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "exit2",
                            file1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "edit1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "propiedades1",
                            edit1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "plugins1",
                            edit1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "separador1",
                            edit1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "channels1",
                            edit1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "vista1",
                            menubar1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (vista1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "go_fullscreen1",
                            vista1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (vista1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "go_windowed1",
                            vista1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "go_zapping1",
                            menubar1_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (go_zapping1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "channel_up1",
                            go_zapping1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (go_zapping1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "channel_down1",
                            go_zapping1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "help1",
                            menubar1_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "about1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gnome_app_add_toolbar (GNOME_APP (zapping), GTK_TOOLBAR (toolbar1), "toolbar1",
                                GNOME_DOCK_ITEM_BEH_EXCLUSIVE,
                                GNOME_DOCK_TOP, 1, 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar1), 16);
  gtk_toolbar_set_space_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_SPACE_LINE);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar1), GTK_RELIEF_NONE);

  Channels = gtk_option_menu_new ();
  gtk_widget_ref (Channels);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "Channels", Channels,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Channels);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), Channels, NULL, NULL);
  Channels_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (Channels), Channels_menu);

  Inputs = gtk_option_menu_new ();
  gtk_widget_ref (Inputs);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "Inputs", Inputs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Inputs);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), Inputs, NULL, NULL);
  Inputs_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (Inputs), Inputs_menu);

  Standards = gtk_option_menu_new ();
  gtk_widget_ref (Standards);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "Standards", Standards,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Standards);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), Standards, NULL, NULL);
  Standards_menu = gtk_menu_new ();
  gtk_option_menu_set_menu (GTK_OPTION_MENU (Standards), Standards_menu);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (zapping, GNOME_STOCK_PIXMAP_EXEC);
  button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Controls"),
                                _("Configure capture"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (zapping, GNOME_STOCK_PIXMAP_PREFERENCES);
  screenshot = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Screenshot"),
                                _("Save a screenshot as PNG"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (screenshot);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "screenshot", screenshot,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot);

  tv_screen = gtk_drawing_area_new ();
  gtk_widget_ref (tv_screen);
  gtk_object_set_data_full (GTK_OBJECT (zapping), "tv_screen", tv_screen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tv_screen);
  gnome_app_set_contents (GNOME_APP (zapping), tv_screen);

  gtk_signal_connect (GTK_OBJECT (zapping), "delete_event",
                      GTK_SIGNAL_FUNC (on_zapping_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_controls_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshot), "clicked",
                      GTK_SIGNAL_FUNC (on_screenshot_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (tv_screen), "size_allocate",
                      GTK_SIGNAL_FUNC (on_tv_screen_size_allocate),
                      NULL);

  return zapping;
}

GtkWidget*
create_channel_window (void)
{
  GtkWidget *channel_window;
  GtkWidget *vbox1;
  GtkWidget *label1;
  GtkWidget *vbox2;
  GtkWidget *country_options_menu;
  GtkWidget *country_options_menu_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist1;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *channel_name;
  GtkWidget *scrolledwindow1;
  GtkWidget *channel_list;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *add_channel;
  GtkWidget *remove_channel;
  GtkWidget *channels_done;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  channel_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (channel_window), "channel_window", channel_window);
  gtk_window_set_title (GTK_WINDOW (channel_window), _("Channel choosing"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (channel_window), vbox1);

  label1 = gtk_label_new (_("Choose here the channels you want to use.\nIf your country is not listed, please find out the frequencies used for\nthe channels, and mail them to the author so they can get included\nin the next release of this program."));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox1), label1, FALSE, FALSE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  country_options_menu = gtk_option_menu_new ();
  gtk_widget_ref (country_options_menu);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "country_options_menu", country_options_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (country_options_menu);
  gtk_box_pack_start (GTK_BOX (vbox2), country_options_menu, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, country_options_menu, _("Select here the country you are in"), NULL);
  country_options_menu_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Dummy country"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (country_options_menu_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (country_options_menu), country_options_menu_menu);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist1 = gtk_clist_new (2);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 143);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label5 = gtk_label_new (_("Channel"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label5);

  label6 = gtk_label_new (_("Freq (kHz)"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label6);

  channel_name = gtk_entry_new ();
  gtk_widget_ref (channel_name);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "channel_name", channel_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (channel_name);
  gtk_box_pack_start (GTK_BOX (vbox2), channel_name, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, channel_name, _("Enter here the name you want to give to this channel"), NULL);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  channel_list = gtk_clist_new (3);
  gtk_widget_ref (channel_list);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "channel_list", channel_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (channel_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), channel_list);
  gtk_clist_set_column_width (GTK_CLIST (channel_list), 0, 78);
  gtk_clist_set_column_width (GTK_CLIST (channel_list), 1, 102);
  gtk_clist_set_column_width (GTK_CLIST (channel_list), 2, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (channel_list), GTK_SELECTION_EXTENDED);
  gtk_clist_column_titles_show (GTK_CLIST (channel_list));

  label2 = gtk_label_new (_("Channel name"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (channel_list), 0, label2);

  label3 = gtk_label_new (_("Real Channel"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (channel_list), 1, label3);

  label4 = gtk_label_new (_("Frequence (kHz)"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_clist_set_column_widget (GTK_CLIST (channel_list), 2, label4);

  add_channel = gnome_stock_button (GNOME_STOCK_BUTTON_YES);
  gtk_widget_ref (add_channel);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "add_channel", add_channel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_channel);
  gtk_box_pack_start (GTK_BOX (vbox2), add_channel, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, add_channel, _("Click here to add current channel"), NULL);

  remove_channel = gnome_stock_button (GNOME_STOCK_BUTTON_NO);
  gtk_widget_ref (remove_channel);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "remove_channel", remove_channel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (remove_channel);
  gtk_box_pack_start (GTK_BOX (vbox2), remove_channel, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, remove_channel, _("Click here to delete selected channels"), NULL);

  channels_done = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (channels_done);
  gtk_object_set_data_full (GTK_OBJECT (channel_window), "channels_done", channels_done,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (channels_done);
  gtk_box_pack_start (GTK_BOX (vbox1), channels_done, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, channels_done, _("Click here when you are done"), NULL);

  gtk_signal_connect (GTK_OBJECT (channel_window), "delete_event",
                      GTK_SIGNAL_FUNC (on_channel_window_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "select_row",
                      GTK_SIGNAL_FUNC (on_clist1_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (add_channel), "clicked",
                      GTK_SIGNAL_FUNC (on_add_channel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (remove_channel), "clicked",
                      GTK_SIGNAL_FUNC (on_remove_channel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (channels_done), "clicked",
                      GTK_SIGNAL_FUNC (on_channels_done_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (channel_window), "tooltips", tooltips);

  return channel_window;
}

GtkWidget*
create_zapping_properties (void)
{
  GtkWidget *zapping_properties;
  GtkWidget *notebook1;
  GtkWidget *vbox3;
  GtkWidget *label8;
  GtkWidget *entry1;
  GtkWidget *label9;
  GtkWidget *fileentry1;
  GtkWidget *combo_entry1;
  GtkWidget *checkbutton1;
  GtkWidget *label7;
  GtkWidget *vbox4;
  GtkWidget *label13;
  GtkWidget *checkbutton2;
  GtkWidget *label11;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label12;
  GtkWidget *fileentry2;
  GtkWidget *combo_entry2;
  GtkWidget *label10;
  GtkWidget *vbox5;
  GtkWidget *label15;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *label14;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  zapping_properties = gnome_property_box_new ();
  gtk_object_set_data (GTK_OBJECT (zapping_properties), "zapping_properties", zapping_properties);

  notebook1 = GNOME_PROPERTY_BOX (zapping_properties)->notebook;
  gtk_object_set_data (GTK_OBJECT (zapping_properties), "notebook1", notebook1);
  gtk_widget_show (notebook1);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  label8 = gtk_label_new (_("File prefix: (saved files will be called prefix1.png, prefix2.png, ...)"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox3), label8, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox3), entry1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry1, _("Enter here the saved file prefix"), NULL);

  label9 = gtk_label_new (_("Screenshot dir"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (vbox3), label9, FALSE, FALSE, 0);

  fileentry1 = gnome_file_entry_new (NULL, _("Screenshot directory"));
  gtk_widget_ref (fileentry1);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "fileentry1", fileentry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fileentry1);
  gtk_box_pack_start (GTK_BOX (vbox3), fileentry1, FALSE, FALSE, 0);
  gnome_file_entry_set_directory (GNOME_FILE_ENTRY (fileentry1), TRUE);

  combo_entry1 = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry1));
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);

  checkbutton1 = gtk_check_button_new_with_label (_("Show progress bar while saving"));
  gtk_widget_ref (checkbutton1);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "checkbutton1", checkbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (vbox3), checkbutton1, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton1), TRUE);

  label7 = gtk_label_new (_("PNG capture"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label7);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  label13 = gtk_label_new (_("(This changes will be applied when the video engine is restarted)"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (vbox4), label13, FALSE, FALSE, 0);

  checkbutton2 = gtk_check_button_new_with_label (_("Capture interlaced (allows higher resolutions)"));
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_box_pack_start (GTK_BOX (vbox4), checkbutton2, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("Number of capture buffers we should try to use:"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (vbox4), label11, FALSE, FALSE, 0);

  spinbutton1_adj = gtk_adjustment_new (8, 4, 64, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_ref (spinbutton1);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "spinbutton1", spinbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (vbox4), spinbutton1, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton1), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spinbutton1), GTK_UPDATE_IF_VALID);

  label12 = gtk_label_new (_("Video device to open (usually /dev/video0)"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (vbox4), label12, FALSE, FALSE, 0);

  fileentry2 = gnome_file_entry_new (NULL, _("Select video device"));
  gtk_widget_ref (fileentry2);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "fileentry2", fileentry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fileentry2);
  gtk_box_pack_start (GTK_BOX (vbox4), fileentry2, FALSE, FALSE, 0);

  combo_entry2 = gnome_file_entry_gtk_entry (GNOME_FILE_ENTRY (fileentry2));
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  label10 = gtk_label_new (_("Video Options"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label10);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox5);

  label15 = gtk_label_new ("");
  gtk_label_parse_uline (GTK_LABEL (label15),
                         _("Verbosity value given to zapping_setup_fb (a suid helper program)"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (vbox5), label15, FALSE, FALSE, 0);

  spinbutton2_adj = gtk_adjustment_new (2, 0, 2, 1, 1, 1);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_ref (spinbutton2);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "spinbutton2", spinbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton2);
  gtk_box_pack_start (GTK_BOX (vbox5), spinbutton2, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton2), TRUE);

  checkbutton3 = gtk_check_button_new_with_label (_("Try to avoid noise when changing TV channels"));
  gtk_widget_ref (checkbutton3);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "checkbutton3", checkbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton3);
  gtk_box_pack_start (GTK_BOX (vbox5), checkbutton3, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("Miscelaneous"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (zapping_properties), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label14);

  gtk_signal_connect (GTK_OBJECT (zapping_properties), "apply",
                      GTK_SIGNAL_FUNC (on_zapping_properties_apply),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (zapping_properties), "help",
                      GTK_SIGNAL_FUNC (on_zapping_properties_help),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (zapping_properties), "tooltips", tooltips);

  return zapping_properties;
}

GtkWidget*
create_about2 (void)
{
  const gchar *authors[] = {
    "Iñaki García Etxebarria",
    NULL
  };
  GtkWidget *about2;

  about2 = gnome_about_new ("Zapping", VERSION,
                        _("(C) Iñaki García Etxebarria"),
                        authors,
                        _("A TV viewer for the Gnome Desktop Environment"),
                        "zapping/0.3-logo.png");
  gtk_object_set_data (GTK_OBJECT (about2), "about2", about2);
  gtk_window_set_modal (GTK_WINDOW (about2), TRUE);

  return about2;
}

GtkWidget*
create_plugin_properties (void)
{
  GtkWidget *plugin_properties;
  GtkWidget *vbox6;
  GtkWidget *vbox7;
  GtkWidget *scrolledwindow3;
  GtkWidget *clist2;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *scrolledwindow4;
  GtkWidget *text1;
  GtkWidget *hbox2;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  plugin_properties = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (plugin_properties), "plugin_properties", plugin_properties);
  gtk_widget_set_usize (plugin_properties, 472, 346);
  gtk_window_set_title (GTK_WINDOW (plugin_properties), _("Plugin properties"));

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (plugin_properties), vbox6);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox7, TRUE, TRUE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox7), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist2 = gtk_clist_new (4);
  gtk_widget_ref (clist2);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "clist2", clist2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), clist2);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 145);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 2, 50);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 3, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (clist2), GTK_SELECTION_EXTENDED);
  gtk_clist_column_titles_show (GTK_CLIST (clist2));

  label16 = gtk_label_new (_("Canonical Name"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, label16);

  label17 = gtk_label_new (_("Name"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, label17);

  label18 = gtk_label_new (_("Version"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 2, label18);

  label19 = gtk_label_new (_("Active"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 3, label19);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox7), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  text1 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text1);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "text1", text1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), text1);

  hbox2 = gtk_hbox_new (TRUE, 14);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox2, FALSE, FALSE, 0);

  button3 = gnome_stock_button (GNOME_STOCK_BUTTON_OK);
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox2), button3, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button3, _("Click here when you are done with the plugins"), NULL);

  button4 = gnome_stock_button (GNOME_STOCK_BUTTON_CLOSE);
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox2), button4, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button4, _("Close the plugin"), NULL);

  button5 = gnome_stock_button (GNOME_STOCK_BUTTON_APPLY);
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (plugin_properties), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox2), button5, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, button5, _("Click here to apply (activate) the plugin"), NULL);

  gtk_signal_connect (GTK_OBJECT (plugin_properties), "delete_event",
                      GTK_SIGNAL_FUNC (on_plugin_properties_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist2), "select_row",
                      GTK_SIGNAL_FUNC (on_clist2_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_plugin_close_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_plugin_apply_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (plugin_properties), "tooltips", tooltips);

  return plugin_properties;
}

