/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Format:");
gchar *s = N_("What to do with the compressed stream");
gchar *s = N_("Save to file");
gchar *s = N_("/dev/null");
gchar *s = N_("Write the encoded stream to:");
gchar *s = N_("MPEG file destination");
gchar *s = N_("Sets the dir where the encoded clips will be written to");
gchar *s = N_("Engine verbosity (output goes to stderr):");
gchar *s = N_("Input / output");
gchar *s = N_("Codec:");
gchar *s = N_("Capture Width:");
gchar *s = N_("Capture Height:");
gchar *s = N_("Video");
gchar *s = N_("Codec:");
gchar *s = N_("Audio");
gchar *s = N_("Saving MPEG");
gchar *s = N_("Press this when you are done");
gchar *s = N_("RTE id (for debugging)");
gchar *s = N_("Destination");
gchar *s = N_("Mux mode");
gchar *s = N_("Some more info: bit rates");
gchar *s = N_("Dynamic stats (dropped, output M's, etc)");
gchar *s = N_("Save mpeg");
gchar *s = N_("Configure the properties for this plugin");
gchar *s = N_("Configure");
gchar *s = N_("Destination file:");
gchar *s = N_("Destination file");
gchar *s = N_("Record");
gchar *s = N_("Format:");
gchar *s = N_("Save as:");
gchar *s = N_("Configure...");
gchar *s = N_("Destination file");
gchar *s = N_("%P %%");
gchar *s = N_("Stop");
gchar *s = N_("Record");
gchar *s = N_("Pause");
gchar *s = N_("window4");
gchar *s = N_("Format:");
gchar *s = N_("New");
gchar *s = N_("Delete");
gchar *s = N_("Codec:");
gchar *s = N_("File format");
gchar *s = N_("Codec:");
gchar *s = N_("Capture Width:");
gchar *s = N_("Capture Height:");
gchar *s = N_("Video");
gchar *s = N_("Codec:");
gchar *s = N_("Audio");
gchar *s = N_("New Format");
gchar *s = N_("Format name:");
