/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("What to do with the compressed stream");
gchar *s = N_("Save to file");
gchar *s = N_("/dev/null");
gchar *s = N_("Whether to encode audio and/or video");
gchar *s = N_("Audio only");
gchar *s = N_("Video only");
gchar *s = N_("Audio and Video");
gchar *s = N_("Use motion compensation");
gchar *s = N_("Write the encoded stream to:");
gchar *s = N_("MPEG file destination");
gchar *s = N_("Sets the dir where the encoded clips will be written to");
gchar *s = N_("Capture Width:");
gchar *s = N_("Capture Height:");
gchar *s = N_("Input / output");
gchar *s = N_("Output video Mbits per second:");
gchar *s = N_("Engine verbosity (output goes to stderr):");
gchar *s = N_("Compression parameters");
gchar *s = N_("Capture Width:");
gchar *s = N_("Capture Height:");
gchar *s = N_("Codec:");
gchar *s = N_("Video");
gchar *s = N_("Select the audio input type you would like to use");
gchar *s = N_("Audio device");
gchar *s = N_("Select the audio device to open");
gchar *s = N_("Audio device:");
gchar *s = N_("Codec:");
gchar *s = N_("Audio");
gchar *s = N_("Saving MPEG");
gchar *s = N_("Press this when you are done");
gchar *s = N_("RTE id (for debugging)");
gchar *s = N_("Destination");
gchar *s = N_("Mux mode");
gchar *s = N_("Some more info: bit rates");
gchar *s = N_("Dynamic stats (dropped, output M's, etc)");
