#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_STPCPY
#undef HAVE_LC_MESSAGES
#undef HAVE_LIBSM
#undef HAVE_LIBXV
#undef HAVE_LIBXDPMS
#undef HAVE_LIBPNG
#undef HAVE_LIBUNICODE
#undef PACKAGE_LOCALE_DIR
#undef PACKAGE_DATA_DIR
#undef PACKAGE_LIB_DIR
#undef PACKAGE_PIXMAPS_DIR
#undef PACKAGE_SOURCE_DIR
#undef DISABLE_X_EXTENSIONS
#undef LIBXML_CHILDS
#undef LIBXML_xmlDocGetRootElement
#undef HAVE_LIBJPEG
#undef HAVE_LIBRTE
#undef HAVE_LIRC
#undef TVENG_ENABLE_IOCTL_TESTS
#undef ENABLE_V4L
// Set if MMX support will be built
#undef USE_MMX
// Architecture
#undef __i386__
#undef __alpha__
#undef __ppc__
#undef __sparc__
