#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef HAVE_LIBSM
#undef HAVE_LIBXV
#undef PACKAGE_LOCALE_DIR
#undef PACKAGE_DATA_DIR
#undef PACKAGE_SOURCE_DIR
#undef DISABLE_X_EXTENSIONS
#undef LIBXML_CHILDS
#undef LIBXML_NO_ROOT
#undef HAVE_GDKPIXBUF
#undef TVENG_DISABLE_IOCTL_TESTS
#undef TVENG_DEBUG
// Set if MMX support will be built
#undef USE_MMX
// Architecture
#undef __i386__
#undef __alpha__
#undef __ppc__
#undef __sparc__
