/*
 *  Emulation of the SSE2 floating point functions
 */

#include "mmx-emu.h"
#include "macros.h"

MMX_EMU_NI_MACRO(cvtsi2ss)
MMX_EMU_NI_MACRO(cvttss2si)
MMX_EMU_NI_MACRO(cvtss2si)
MMX_EMU_NI_MACRO(rcpss)
MMX_EMU_NI_MACRO(rsqrtss)
MMX_EMU_NI_MACRO(addss)
MMX_EMU_NI_MACRO(mulss)
MMX_EMU_NI_MACRO(cvtss2sd)
MMX_EMU_NI_MACRO(cvttps2dq)
MMX_EMU_NI_MACRO(subss)
MMX_EMU_NI_MACRO(minss)
MMX_EMU_NI_MACRO(divss)
MMX_EMU_NI_MACRO(maxss)
MMX_EMU_NI_MACRO(movdqu2xmm)
MMX_EMU_NI_MACRO(movdqu2mem)
MMX_EMU_NI_MACRO(cmpss)
MMX_EMU_NI_MACRO(movq2dq)
MMX_EMU_NI_MACRO(cvtdq2pd)

MMX_EMU_NI_MACRO(movsd)
MMX_EMU_NI_MACRO(cvtsi2sd)
MMX_EMU_NI_MACRO(cvttsd2si)
MMX_EMU_NI_MACRO(cvtsd2si)
MMX_EMU_NI_MACRO(sqrtsd)
MMX_EMU_NI_MACRO(addsd)
MMX_EMU_NI_MACRO(mulsd)
MMX_EMU_NI_MACRO(cvtsd2ss)
MMX_EMU_NI_MACRO(subsd)
MMX_EMU_NI_MACRO(minsd)
MMX_EMU_NI_MACRO(divsd)
MMX_EMU_NI_MACRO(maxsd)
MMX_EMU_NI_MACRO(cmpsd)
MMX_EMU_NI_MACRO(movdq2q)
MMX_EMU_NI_MACRO(cvtpd2dq)
MMX_EMU_NI_MACRO(movss2mem)

MMX_EMU_NI_MACRO(movupd)
MMX_EMU_NI_MACRO(movlpd2mem)
MMX_EMU_NI_MACRO(movlpd2xmm)
MMX_EMU_NI_MACRO(unpcklpd)
MMX_EMU_NI_MACRO(unpckhpd)
MMX_EMU_NI_MACRO(movhpd2mem)
MMX_EMU_NI_MACRO(movhpd2xmm)
MMX_EMU_NI_MACRO(cvtpi2pd)
MMX_EMU_NI_MACRO(movapd2mem)
MMX_EMU_NI_MACRO(movapd2xmm)
MMX_EMU_NI_MACRO(movntpd)
MMX_EMU_NI_MACRO(movnti)
MMX_EMU_NI_MACRO(cvttpd2pi)
MMX_EMU_NI_MACRO(cvtpd2pi)
MMX_EMU_NI_MACRO(ucomisd)
MMX_EMU_NI_MACRO(comisd)
MMX_EMU_NI_MACRO(movmskpd)
MMX_EMU_NI_MACRO(sqrtpd)
MMX_EMU_NI_MACRO(andpd)
MMX_EMU_NI_MACRO(andnpd)
MMX_EMU_NI_MACRO(orpd)
MMX_EMU_NI_MACRO(xorpd)
MMX_EMU_NI_MACRO(addpd)
MMX_EMU_NI_MACRO(mulpd)
MMX_EMU_NI_MACRO(cvtpd2ps)
MMX_EMU_NI_MACRO(cvtps2dq)
MMX_EMU_NI_MACRO(subpd)
MMX_EMU_NI_MACRO(minpd)
MMX_EMU_NI_MACRO(divpd)
MMX_EMU_NI_MACRO(maxpd)
MMX_EMU_NI_MACRO(cmppd)
MMX_EMU_NI_MACRO(shufpd)
MMX_EMU_NI_MACRO(cvttpd2dq)
