/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Select here the directory where screenshots will be saved");
gchar *s = N_("Select directory to save screenshots");
gchar *s = N_("After saving the screenshot, run the command:");
gchar *s = N_("If this entry isn't empty, Zapping will try to run the given command each time you save a screenshot.");
gchar *s = N_("Preview");
gchar *s = N_("Grab on clicking OK");
gchar *s = N_("Skip one picture before grabbing");
gchar *s = N_("Entering file name closes dialog");
gchar *s = N_("Save screenshot");
gchar *s = N_("Configure the properties for this plugin");
gchar *s = N_("Configure");
gchar *s = N_("Save as:");
gchar *s = N_("Destination file");
gchar *s = N_("Quality:");
gchar *s = N_("Format:");
gchar *s = N_("Preview");
gchar *s = N_("Deinterlace:");
gchar *s = N_("Off");
gchar *s = N_("Forward");
gchar *s = N_("Backward");
