.TH MP1E 1 "$Date: 2002-02-09 07:24:41 $" "mp1e manual" \" -*- nroff -*-
.SH NAME
mp1e \- realtime MPEG-1 audio/video encoder
.SH SYNOPSIS
mp1e [options] [<Config File] >MPEG stream
.SH DESCRIPTION
.B mp1e
reads images from a V4L or V4L2 compatible device, audio samples from
a OSS, ALSA or ESD compatible device or file, encodes them as MPEG-1
a/v stream and writes the result to standard output.
.P
Note
.B mp1e
runs fastest, and audio synchronization (including clock drift compensation)
is best when using V4L2 and ALSA or native OSS. The V4L interface is slow
and not frequently tested because I don't have a V4L device. Bug reports are
welcome, patches even more. See the bottom of this manual page for contact
addresses. Contributors will be supported as much as possible and adequately
credited.
.P
An MMX enhanced x86 CPU is required, this should be at least a Pentium
II 400 or equivalent. Without motion compensation a Pentium II 233 is
more than sufficient, I-only compression (comparable to MJPEG) works
on any MMX CPU and audio is usually negligible. The resources needed
for compression depend on several factors, so the actual requirements
may be lesser or greater than estimated above.
.P
If available,
.B mp1e
takes advantage of 3DNow!, SSE and SSE2 extensions for motion
compensation. This is work in progress, so don't expect a huge
improvement yet.
.SH OPTIONS
Options in short (-a) and long (--audio_mode) format are supported.
Some options take numbers or keywords as arguments, for example:
-a 0 -a0 -a stereo --audio_mode=stereo 
.P
.TP
.BI "\-a, \-\-audio_mode " "0 stereo | 2 dual_channel | 3 mono"
.RS
Determines the audio matrix, default is mono. Stereo and dual channel
are identical except for a flag in the stream which tells the player
not to mix the left and right channel in dual channel mode (e.g. for
bilingual programs). MPEG-1/2 Layer II joint stereo is not supported
yet.
.P
.B mp1e
will automatically select an appropriate level of psychoacoustic
analysis. You can force medium quality psychoacoustic analysis by
adding 10, full quality by adding 20 to the -a parameter.
.RE
.TP
.BI "\-b, \-\-video_bit_rate " float
.RS
Output bit rate of the video stream, a floating point number of
e.g. 3.5 (Mbit/s) or 3500 (kbit/s). Reasonable values are between
1.0 - 2.5 Mbit/s at 352 x 288 resolution, the default is 2.3 Mbit/s.
.P
Higher bit rates improve the compression quality but also add to
the CPU load. Please remember MPEG is a lossy compression standard,
and this encoder may not achieve near lossless quality at any
bit rate. (Versions before 1.8 suffered from a possible
quantization overflow at very high bit rates, this has been
fixed with a requantization algorithm.)
.P
.B mp1e
uses a constant bit rate algorithm, it will adjust the
compression quality in an attempt to meet the requested bit rate.
Variable bit rate encoding is planned for a later date.
.RE
.TP
.BI "\-c, \-\-capture_device " name
.RS
The video capture device, default
.I /dev/video.
V4L and V4L2 devices are automatically detected. Alternatively one
can compress from files, this is mainly intended for debugging:
.I anyname.ppm.
A printf-style integer conversion spec (%d, %02u, %3x) can be
inserted to stand for numbers zero and up. For example img%04u.ppm
will read img0000.ppm, img0001.ppm and so forth until there is no
image of that name.
.P
As of version 1.9 the V4L interface is out of order. Contributions
welcome.
.RE
.TP
.BI "\-e, \-\-skip_method " "0 compatible | 1 mux | 2 fake_picture"
.RS
Reducing the video frame rate (see option
.B -f
) has certain side effects, thus
.B mp1e
offers two alternative methods to skip frames, albeit incompatible
with the MPEG-1 standard and thus not supported by all players.
.P
The -e mux or -e1 method completely removes skipped frames from the
stream. When the player is unable to deduce the actual frame rate
from the MPEG system (audio and video) stream timestamps, you have
to tell the player the actual frame rate by other means, such as a
command line option. You can e.g. add -fps actual_frame_rate to
Mplayer.
.P
The -e fake_picture or -e2 method additionally inserts a fake picture
code in place of skipped frames to maintain the nominal frame rate,
however players may abort on encounter of an invalid picture code.
.RE
.TP
.BI "\-f, \-\-frame_rate " float
.RS
How many video frames to compress per second, defaults to the
current video standard reported by the capture device (25 or
30 Hz) or 24 Hz when compressing from a file. Smaller numbers
can dramatically reduce the CPU load and the required bit rate.
.P
MPEG-1 knows only a number of discrete frame rates, so
.B mp1e
will encode the next higher frame rate and selectively drop
frames. Any player should play these streams at the correct rate.
There is one major side effect however, frame dropping may
eliminate some or all B pictures from the GOP (see option
.B -g
), the
.B -e
option offers alternatives.
.P
Also, with increasing frame distances P pictures and motion
compensation become less effective, requiring a higher bit
rate.
.P
Frame dropping will inevitable occur on a general purpose
multitasking OS (as opposed to a real-time OS), this has been
addressed. So there is no reason to reduce the frame rate
when the CPU is too slow,
.B mp1e
does the right thing automagically.
.RE
.TP
.BI "\-g, \-\-gop_sequence " string
.RS
An MPEG-1 video stream consists of a repeating sequence of picture
types, the "group of pictures". These are:
.IP "I - Intra coded"
These pictures can be decoded on their own, which is useful for
editing and for random access into a stream. Intra pictures
compress fastest but have the worst compression ratio.
.IP "P - Predictive coded"
.RS
Acknowledging that movie pictures usually don't change much from
one to another this picture type encodes only the difference to
the previous I or P picture. P pictures give typically better
quality than I pictures, at the cost of doubling, with motion
compensation even multiplying the compression time.
.P
You should avoid extremely long sequences of P pictures as the
prediction error (caused by inaccuracies in the encoder and
decoder transformation functions) can accumulate.
.RE
.IP "B - Bidirectional predictive coded"
.RS
These pictures are predicted from the closest I or P picture,
either the previous, next, or both references, and exhibit the
greatest potential compression ratio. Since B pictures are
not references for P or B pictures they compress faster than
P pictures, but the motion compensation effort doubles.
.P
Prediction and motion compensation become less effective
and more computationally demanding at increasing frame
distances, so it makes little sense to request more than
two or three B pictures in a row. A special case are
cartoons, which are often produced at lower frame rates
of 15 or 24 Hz. An IP-only sequence may be more efficient
here.
.RE
.P
"D" pictures (ultra low quality for streaming fast forward and
such) are not supported.
.P
You can enter any GOP sequence of "I", "P" and "B"
(displayed, not coded order), provided it starts with "I"
and does not exceed 1023 pictures. The default is
"IBBPBBPBBPBBP".
.B mp1e
will override the sequence when a) frame dropping occurs,
b) promote a P to an I picture when prediction appears
ineffective (e.g. at scene cuts); Promoting B pictures
is not implemented yet. c) at the end of a stream.
.RE
.TP
.BI "\-h, \-\-help"
Print a usage message listing all available options, then exit.
.TP
.BI "\-i, \-\-config " filename
.RS
Read more options from a configuration file. This is also useful
to nest configuration files. Example:
.P
mp1e -i lowaudio.conf -i small_letterbox.conf >mymovie.mpg
.P
Options, later ones taking priority, are read from these sources
at startup:
.IP \(bu
/usr/local/etc/mp1e.conf (system wide)
.IP \(bu
~/.mp1erc (user)
.IP \(bu
standard input if a file
.IP \(bu
the command line
.P
The configuration file syntax is straightforward. Anything after
a hash mark (#) is a comment and ignored. Put one option
on each line as with --long options but without the dashes (--).
Trailing garbage (here: "Mbit/s") is ignored. For example:
.P
# This is a comment
.P
video_bit_rate = 2.3 Mbit/s
.P
mux_mode = video_and_audio
.RE 
.TP
.BI "\-l, \-\-letterbox"
This is a shortcut to reduce the compressed image size by
2/8 of its current height. Although letterbox bars compress
rather nicely, it's still a waste of CPU time and stream
bandwidth, so excluding them is generally a good idea.
.TP
.BI "\-m, \-\-mux_mode " "1 video | 2 audio | 3 video_and_audio"
Enables compression of only video, only audio, or both. Default is
both.
.TP
.BI "\-n, \-\-num_frames " n or h:m[:s]
.RS
Terminate compression after exactly n video frames, including
dropped ones, or the given time. In PAL/SECAM countries there
are 25 frames per second, in NTSC countries 30, and in some other
countries which couldn't decide between straight PAL and NTSC one
has to guess.
.P
In audio only mode the frame number n refers to audio frames of
1152 samples each (regardless of stereo or dual channel mode).
.P
The other method to stop compression is to hit Ctrl-C or to
send the process a SIGUSR1 signal.
.RE
.TP
.BI "\-o, \-\-outputfile " name
.RS
Instead of writing to standard output, create a file and store
the output there.
.RE
.TP
.BI "\-p, \-\-pcm_device " name
.RS
Specifies the audio capture device.
.IP \(bu
For OSS devices (Open Sound System, as shipped with Linux 2.2 and
2.4 kernels) this is usually "/dev/dsp".
.IP \(bu
If you have ALSA 0.5 installed (libasound)
use "alsa-c,d" where c stands for the card number and
d for the device number, usually both zero. If you have ALSA
0.9 installed enter "alsa/device_name", for example "alsa/default".
The ALSA 0.9 interface is experimental, in other words it doesn't
work for me (but so does arecord) and sync is still suboptimal. In
either case "alsa" alone will select the default device.
.IP \(bu
To capture audio from ESD (the Enlightened Sound Daemon), write "esd".
.IP \(bu
To encode audio from a file using libaudiofile (AIFF, WAV, .au format
etc) specify the file name and then add -v and watch it fly. :-) The
sampling frequency and number of channels encoded in the file take
priority over the respective
.B mp1e
options. Sorry, no conversion. The video stream, if any, is synchronized by
assuming audio starts at the same instant the first video frame has
been captured and the audio data is subject to clock drift compensation
taking the video clock as reference. (Any stream or the system clock
could be reference, but there's no command line option yet.)
.P
Type
.B mp1e -h
to see the default PCM device.
.RE
.TP
.BI "\-r, \-\-rec_source " n,m
.RS
This is an option for people notoriously forgetting to
fire up a mixer application an set the proper inputs,
like me. You may want to add it to your configuration
file, see option
.B -i.
.P
.I n
is the number of one of several audio sources. It depends
on your audio hardware which sources are available,
type
.B mp1e -h
for a list.
.I m
is the recording volume, a number between 0-100, zero
stands for silence of course. On exit
.B mp1e
restores the previous settings.
.P
The default mixer device (OSS) is "/dev/mixer", this can
can be changed, or mixer access completely disabled, with the
.B -x
option.
.RE
.TP
.BI "\-s, \-\-image_size " wxh
.RS
The image size is given in pixels and must lie between 1x1
and 4095x4095. Although not strictly required it should be
a multiple of 16x16 pixels. An MPEG stream consists of blocks
of 16x16 pixels each, other sizes have to encode padding pixels
which are clipped away by the player and thus wasted.
.P
Further, if the requested image size is smaller than the
capture size (see
.B -G
option), the source rectangle will be
centred over the captured image. This cannot work if the
encoded image is less than 16 pixels smaller on each side
than the captured image. Also a source rectangle which isn't
aligned to 16x16 blocks will slightly slow down the compression.
.P
Typical sizes for MPEG-1 video are 320x240, 320x256, 352x288
and 384x288. You can also encode at typical MPEG-2 sizes of
720x480 or 720x576, but mind that MPEG-1 supports only
progressive, not interlaced video. That means film which
has been transferred to PAL or SECAM video will compress
nicely. Otherwise compression quality can suffer from
the high spatial frequencies introduced by motions from
one field to the next. See option
.B -F
for a possible remedy.
.RE
.TP
.BI "\-v, \-\-verbose"
Increase the verbosity of
.B mp1e,
the default is silence. Prints on standard error.
.TP
.BI "\-w, \-\-mono"
Encode only luminance information. This is useful for recording old
black and white movies, the purpose is to eliminate color
distortions. Don't expect an impact on the bit rate or compression
time.
.TP
.BI "\-x, \-\-mixer_device"
.RS
Specifies the OSS mixer device to select the recording source and
volume. The default is "/dev/mixer". See also the
.B -r
option. To disable initialization of the mixer enter a phony name,
for example "~/no_mixer_device".
.RE
.TP
.BI "\-A, \-\-anno " string
Include an annotation in the MPEG user_data field of the first stream
header encoded, a few bytes after the start of the stream. This is
an
.B mp1e
feature, nothing standardized, and will be ignored by players.
.RE
.TP
.BI "\-B, \-\-audio_bit_rate " float
.RS
Total output bit rate of the audio stream, regardless of mono,
stereo or dual channel mode. This is a floating point number of
e.g. 128 (kbit/s). Reasonable values are between 40-128 kbit/s
per channel, depending on the sampling rate and the audio quality
you want.
.P
MPEG-1/2 Layer II audio supports several discrete bit rates
between 8-384 kbit/s,
.B mp1e
rounds to the closest possible. Only constant bit rates are
implemented.
.RE
.TP
.BI "\-C, \-\-cpu " type
.RS
You can override automatic CPU detection with this option. At
present the valid types are: pmmx, p2, p3, p4 for the respective
Intel Pentium CPUs; k6-2, k7 for AMD devices (Athlons, Durons
and Athlon 4 are k7); m2 and c3 refer to the Cyrix MII and
Cyrix III CPUs.
.RE
.TP
.BI "\-F, \-\-filter " n
.RS
.B Mp1e
supports the source formats YUV 4:2:0 and 4:2:2, which are selected
as available from your video device. Additionally there are a few
simple pre-processing filters you can enable:
.IP "1 - YUV 4:2:0"
.RS
Force YUV 4:2:0 mode, this is also the fastest mode.
.RE
.IP "2 - fast YUV 4:2:2"
.RS
Force fast YUV 4:2:2 mode.
.RE
.P
All modes below require YUV 4:2:2 support.
.P
.IP "3 - Vertical decimation"
.RS
The capture size requested from the driver is twice the nominal height,
the filter will average the luminance information from every two adjacent
lines and color information from every four. I added this filter to get
smoother pictures at low resolution, e.g. 176 x 144, because my video
hardware would filter only in horizontal direction and simply drop
three of four picture lines.
.P
At higher resolution this will combine the top and bottom field of a
picture, giving smoother motions and also improving the quality when
compressing without motion compensation.
.P
Noise is a major enemy of video compression because it sucks stream
bandwidth for information which is actually redundant. Averaging
has a noise reduction side effect. A negative effect of this filter
is that accessing a larger source image will also slightly slow
down compression.
.RE
.IP "4 - Temporal interpolation"
.RS
Similar to #3 this will average two fields of the same parity, that is
the current and next frame. Practically this filter provides the same
motion smoothing effect for high resolution sources, e.g. 720x576, but
the results are usually bad.
.RE
.IP "5 - Vertical interpolation"
.RS
Averages every current and next line, has a blurring effect.
.RE
.IP "6 - Field progressive"
.RS
Treats the two fields of a picture as individual frames and
encodes them at twice the nominal frame rate, i.e. 50 or 60 Hz.
This will preserve inter field motions, one could say
reproducing video more natural, similar to interlaced video.
Don't forget to double the bit rate.
.P
The V4L2 "both fields" capture mode is required (that is
capturing individual fields, not field pairs), it will not
work with V4L and actually has never been tested anyway.
.RE
.IP "7 - Field progressive with interpolation"
.RS
One problem with filter mode #6 is that fields are shifted
against each other by half a line height, which causes flicker.
This filter additionally averages two adjacent fields of the
same or successive pictures, eliminating the flicker. At
the moment this is as close to a real TV as you can get.
.RE
.P
More filters are available, but these are experimental and
may disappear from future versions. Expect problems when you
request them in your configuration files.
.P
Finally one more tip to get rid of noise: Reduce the contrast,
it does wonders in some cases. (A video controls option is
not included, this is a v4l2 application, you should have a
control panel application around.)
.RE
.TP
.BI "\-G, \-\-grab_size " wxh
.RS
By default, the size of images captured by the video devices will be
the same as the encoded image size (
.B -s
option). To compress only a
subsection of the source image you can request a larger capture
size, which must be supported by your driver.
.P
The capture size is given in pixels. Please note
.B mp1e
cannot properly clip when the encoded image is less than 16 pixels
smaller than the captured image.
.RE
.TP
.BI "\-I, \-\-vbi_device " name
.RS
.B Mp1e
can record Teletext subtitles from a V4L or V4L2 VBI device, which
is specified by this option. The default is "/dev/vbi". See also
option
.B -T.
.RE
.TP
.BI "\-M, \-\-mute " "0 unmute | 1 mute | 2 ignore"
This is a work-around for the bttv driver. On startup a) unmute sound
(if you want to record audio), b) mute, c) ignore the current setting,
which happens to be the default.
.TP
.BI "\-P, \-\-preview"
Secret option to display reconstructed I and P pictures during
compression, plus real-time tinker gadgets (bit rate etc). -PP
previews at macroblock granularity. You need GTK, XVideo and the
feature has to be activated at compile time. At the moment, more
than anything else this is a debugging tool, and it may or may
not work in this version.
.TP
.BI "\-R, \-\-motion " min,max
.RS
Set the motion compensation search range in half samples. These are
absolute limits
.B mp1e
will not exceed under any circumstances, within the hardcoded limits
of 8 x 4 to 64 x 64 (i.e. test motion vectors -8,-4 to +8,+4). When
you omit the maximum value it will be set to the same as minimum.
A value of zero
.B disables motion compensation, which is the default.
.P
Note the actual search range is automatically determined for each
frame, taking the frame distance into account, to keep the bits and
CPU time spent on motion compensation in relation to the actual motion.
So the major purpose of this option is to anticipate a high minimum
(Sports etc.) and to limit the maximum CPU load. A reasonable setting
may be 8,24, but you really have to try yourself, especially at lower
frame rates (greater frame distances) and higher resolution.
.P
This option can greatly affect the CPU load since the effort grows
exponentially with the search range. The quality impact can vary,
depending on the source material.
.P
One flaw of current motion compensation is that search ranges exceeding
the sustained abilities of the CPU lead to frame dropping instead of
reducing the search range, hopefully this will be fixed in later
versions. With motion compensation the number of capture and
intermediate buffers has more impact on CPU load. This is a delicate
matter in terms of audio synchronization, an option to request more
or less buffers is still missing.
.RE
.TP
.BI "\-S, \-\-sampling_rate " float
.RS
Select a sampling rate for audio recording. This can reduce the
required bit rate, but not without a quality loss because compression
already tends to eliminates subjectively redundant higher frequencies.
The impact on CPU load is usually negligible.
.P
MPEG-1 Audio Layer II supports only these sampling rates: 32 kHz, 44.1
kHz, 48 kHz. Additionally you can specify 16 kHz, 22.05 kHz and 24 kHz
which enables the MPEG-2 Layer II Low Frequency Extension. Note some
MPEG players do not support MPEG-2 LFE. Other sampling frequencies are
rounded to the closest allowed by MPEG and supported by your soundcard.
.P
.B mp1e
forces high quality psychoacoustic analysis at very low frequencies,
this will slightly increase the CPU load.
.RE
.TP
.BI "\-T, \-\-subtitle_pages " [nnn,...]
.RS
Specify the Teletext pages which contain subtitles to be recorded, for
example "150,333,777". The actual page contents are irrelevant. You
can also specify a range "3??" or "???" all pages. Without parameters
the page filter is disabled and all Teletext recorded verbatim, e.g.
for broadcasting on a LAN, ~300 kbit/s.
.P
Teletext data is recorded as specified by the DVB standard, which is
most suitable for this purpose. DVB however defines Teletext transport
only for MPEG-2 program streams, which can be enabled for
.B mp1e
with option
.B -X.
The encoding of Teletext in an MPEG-1 system stream
is a non-standard extrapolation, and I am not aware of any program
decoding DVB Teletext at this time. Anyway subtitles can be archived
for later use.
.RE
.TP
.BI "\-V, \-\-version"
Print version information on standard output, then exit.
.TP
.BI "\-X, \-\-mux " "0 nirvana | 1 bypass | 2 mpeg1 | 3 mpeg2-ps | 4 vcd"
A multiplexer combines video, audio and other streams, together with
synchronization information in one "system" stream.
.B Mp1e
provides these multiplexers:
.RS
.IP "0 - nirvana"
.RS
Discard all output. Just as "mp1e >/dev/null", but faster. For
testing purposes.
.RE
.IP "1 - bypass"
.RS
Output an elementary stream. This mux is enabled when you request
compression of video only (-m1) or audio only (-m2), by overriding
the default with the
.B -X
option you can also create a system stream
which contains only one elementary stream.
.RE
.IP "2 - mpeg1"
.RS
Standard MPEG-1 program stream. This mux is enabled when you request
compression of video and audio (-m3), which is the default.
.B Mp1e
versions before 1.8 created incorrect MPEG-1 system streams which
only a few players would accept. Apologies for the inconvenience.
.RE
.IP "3 - mpeg2-ps"
.RS
Standard MPEG-2 program stream (as opposed to a transport stream).
Due to lack of references the syntax has not been verified yet.
.RE
.IP "4 - vcd"
.RS
MPEG-1 program stream in a format suitable for creating VCDs.
For strict VCD compliance you have to set a number of compression
parameters: Image size 352x240 (NTSC) or 352x288 (PAL), bit rate 1152
kbit/s; Audio sampling rate 44.1 kHz, stereo, 225 kbit/s. Otherwise a
hardware player may refuse to play the stream. This multiplexer is
a clone of vcdmplex, the VCD specs are not easily available so I
cannot warrant full compliance.
.P
Frame dropping should be avoided in this mode to prevent hardware
buffer underflows. The reason is that mp1e for now, being designed
to record on harddisk, will not waste space to padding bytes.
.P
To actually create a VCD you need another tool, for example GNU
VCDImager or mkvcdfs from the vcdtools package.
.RE
.SH EXAMPLES
.TP
.BI "mp1e -v >foo.mpg"
Record video and audio with status report.
.TP
.BI "mp1e -m2 >bar.mp2"
Record audio, don't print anything on stderr.
.TP
.BI "mp1e -v -m1 -R8,24 -b1.15 >baz.mpg"
Record video without sound, with motion compensation, at 1.15 Mbit/s.
.TP
.BI "mp1e -v -m2 -a20 -B96 -S32 >john.mp2"
Record stereo audio, best possible quality at 96 kbit/s and
32 kHz sampling rate.
.TP
.BI "mp1e -v -m1 -b208 -s320x256 -gIPPPPPPPP -f3.125 >paul.mpg"
Record video, image size 320 x 256 pixel, 3.125 frames/second (25/8),
GOP IPPPPPPPP, at 208 kbit/s.
.TP
.BI "mp1e -v -b190 -s320x256 -f3.125 -e1 -R8,64 -B48 -S32 >george.mpg"
Record video and audio, image size 320 x 256 pixel, 3.125
frames/second (25/8) using skip method 1, IPB with motion
compensation range 8-64, mono audio at 48 kbit/s, sampling rate 32 kHz,
video bit rate 190 kbit/s.
.TP
.BI "mp1e -v -b4 -s704x576 >ringo.mpg"
Record video 704 x 576 pixels, default IPB without motion
compensation, video bit rate 4 Mbit/s, audio according to
default parameters.
.SH FILES
Optional configuration files:
.IP \(bu
/usr/local/etc/mp1e.conf (system wide)
.IP \(bu
~/.mp1erc (user)
.P
See option
.B -i
for details.
.SH EXIT STATUS
.B mp1e
returns 0 on success, 1 on failure. Policy is to abort in doubt,
to avoid hour long recording of snow or silence and you have
to wait for the next repeat in 2022...
.SH BUGS
Versions prior 1.7 are heavily bugged and should be avoided. Versions
prior 1.8 create invalid stream syntax which only a few players would
accept, and inaccurate predictive coding which has been replaced in
version 1.8.
.P
The ALSA and ESD interface in 1.9 doesn't work properly. Versions prior
1.9.1 can hang due to a sync flaw and won't compile with ALSA devel libs
0.9. The mixer volume wasn't set for the requested but the default PCM
source by versions prior 1.9.2.
.SH AUTHORS
.IP \(em
Michael H. Schimek (mschimek@users.sf.net)
.IP \(em
Iñaki G. Etxebarria (garetxe@users.sf.net)
.P
Thanks to
.IP \(em
Justin Schoeman for the original V4L interface
.IP \(em
Bill Simpson-Young and Conrad Parker for a V4L2 fix
.P
.B mp1e
lives at the
.UR http://zapping.sf.net
Zapping homepage zapping.sf.net
.UE
and at
.UR http://www.ibiblio.org
www.ibiblio.org
.UE
