/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Zapping");
gchar *s = N_("Manages the installed plug-ins");
gchar *s = N_("P_lugins");
gchar *s = N_("Edit here the channels you have tuned");
gchar *s = N_("_TV Channels");
gchar *s = N_("Use this to go fullscreen. Press ESC to return to Windowed mode");
gchar *s = N_("Go _Fullscreen");
gchar *s = N_("Go _Zapping");
gchar *s = N_("Select the previous station in the channel list");
gchar *s = N_("Channel up");
gchar *s = N_("Select the next station in the channel list");
gchar *s = N_("Channel down");
gchar *s = N_("You can get here some info about this program");
gchar *s = N_("_Main help");
gchar *s = N_("Configure capture");
gchar *s = N_("Controls");
gchar *s = N_("Video device capabilities");
gchar *s = N_("label30");
gchar *s = N_("Device name:");
gchar *s = N_("label27");
gchar *s = N_("label31");
gchar *s = N_("Current controller:");
gchar *s = N_("Device file:");
gchar *s = N_("Minimum capture size:");
gchar *s = N_("Maximum capture size:");
gchar *s = N_("label28");
gchar *s = N_("label29");
gchar *s = N_("Device info");
gchar *s = N_("Verbosity value given to zapping_setup_fb:");
gchar *s = N_("The bigger this value is, the more verbose zapping_setup_fb will be");
gchar *s = N_("Avoid noise while changing channels");
gchar *s = N_("Save window geometry (some WM's don't like it)");
gchar *s = N_("Resize using fixed increments");
gchar *s = N_("Start Zapping muted");
gchar *s = N_("Ratio mode:");
gchar *s = N_("No fixed ratio\n"
              "4:3\n"
              "16:9\n"
              "");
gchar *s = N_("General options");
gchar *s = N_("Channel choosing");
gchar *s = N_("Choose here the channels you want to use.\n"
              "If your country is not listed, please find out the frequencies used for\n"
              "the channels, and mail them to the author so they can get included\n"
              "in the next release of this program.");
gchar *s = N_("Select here the country you are in");
gchar *s = N_("Dummy country\n"
              "");
gchar *s = N_("Select here the channel you want to tune");
gchar *s = N_("Channel");
gchar *s = N_("Freq (kHz)");
gchar *s = N_("Alias");
gchar *s = N_("Channel");
gchar *s = N_("Country");
gchar *s = N_("kHz");
gchar *s = N_("Frequence:");
gchar *s = N_("Select your country and click here to search for the available channels");
gchar *s = N_("_Search for the available channels in the current country");
gchar *s = N_("Enter here the alias you want to give to this channel:");
gchar *s = N_("Enter here the name you want to give to this channel");
gchar *s = N_("Click here when you are done");
gchar *s = N_("Click this button if you want to discard current changes");
gchar *s = N_("Click here to add current channel");
gchar *s = N_("_Add");
gchar *s = N_("Click here to apply the current options to the selected channels");
gchar *s = N_("_Modify");
gchar *s = N_("Click here to delete selected channels");
gchar *s = N_("_Remove");
gchar *s = N_("This shows some help about this dialog");
gchar *s = N_("Plugin properties");
gchar *s = N_("Click here when you are done");
gchar *s = N_("Run the plugin");
gchar *s = N_("_Start Plugin");
gchar *s = N_("Stop this plugin");
gchar *s = N_("S_top Plugin");
gchar *s = N_("Show the configuration options for this plugin");
gchar *s = N_("_Configure");
gchar *s = N_("Plugins");
gchar *s = N_("label67 (Plugin name)");
gchar *s = N_("label68 (Plugin short description)");
gchar *s = N_("Canonical name:");
gchar *s = N_("label69");
gchar *s = N_("Author:");
gchar *s = N_("label71");
gchar *s = N_("Plugin version:");
gchar *s = N_("label72");
gchar *s = N_("Plugin priority:");
gchar *s = N_("label73");
gchar *s = N_("Plugin description");
gchar *s = N_("text1");
gchar *s = N_("Properties");
gchar *s = N_("Plugin location");
gchar *s = N_("This is the file where the plugin is located");
gchar *s = N_("text2");
gchar *s = N_("label76");
gchar *s = N_("Symbol");
gchar *s = N_("Hash");
gchar *s = N_("Description of the symbol");
gchar *s = N_("text3");
gchar *s = N_("Advanced");
gchar *s = N_("Use this for starting the fullscreen mode");
gchar *s = N_("Go _Fullscreen");
gchar *s = N_("Searching...");
gchar *s = N_("%P %%");
