/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Zapping");
gchar *s = N_("P_lugins");
gchar *s = N_("_TV Channels");
gchar *s = N_("Use this to go fullscreen. Press ESC to return to Windowed mode");
gchar *s = N_("Go _Fullscreen");
gchar *s = N_("Go _Windowed");
gchar *s = N_("Go _Zapping");
gchar *s = N_("Channel up");
gchar *s = N_("Channel down");
gchar *s = N_("Configure capture");
gchar *s = N_("Controls");
gchar *s = N_("Save a screenshot as PNG");
gchar *s = N_("Screenshot");
gchar *s = N_("Channel choosing");
gchar *s = N_("Choose here the channels you want to use.\n"
              "If your country is not listed, please find out the frequencies used for\n"
              "the channels, and mail them to the author so they can get included\n"
              "in the next release of this program.");
gchar *s = N_("Select here the country you are in");
gchar *s = N_("Dummy country\n"
              "");
gchar *s = N_("Channel");
gchar *s = N_("Freq (kHz)");
gchar *s = N_("Enter here the name you want to give to this channel");
gchar *s = N_("Channel name");
gchar *s = N_("Real Channel");
gchar *s = N_("Frequence (kHz)");
gchar *s = N_("Click here to add current channel");
gchar *s = N_("Click here to delete selected channels");
gchar *s = N_("Click here when you are done");
gchar *s = N_("File prefix: (saved files will be called prefix1.png, prefix2.png, ...)");
gchar *s = N_("Enter here the saved file prefix");
gchar *s = N_("Screenshot dir");
gchar *s = N_("Screenshot directory");
gchar *s = N_("Show progress bar while saving");
gchar *s = N_("PNG capture");
gchar *s = N_("(This changes will be applied when the video engine is restarted)");
gchar *s = N_("Capture interlaced (allows higher resolutions)");
gchar *s = N_("Number of capture buffers we should try to use:");
gchar *s = N_("Video device to open (usually /dev/video0)");
gchar *s = N_("Select video device");
gchar *s = N_("Video Options");
gchar *s = N_("Verbosity value given to zapping_setup_fb (a suid helper program)");
gchar *s = N_("Try to avoid noise when changing TV channels");
gchar *s = N_("Miscelaneous");
gchar *s = N_("(C) Iñaki García Etxebarria");
gchar *s = N_("A TV viewer for the Gnome Desktop Environment");
gchar *s = N_("Plugin properties");
gchar *s = N_("Canonical Name");
gchar *s = N_("Name");
gchar *s = N_("Version");
gchar *s = N_("Active");
gchar *s = N_("Click here when you are done with the plugins");
gchar *s = N_("Close the plugin");
gchar *s = N_("Click here to apply (activate) the plugin");
