/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Number of saved frames:");
gchar *s = N_("This value is computed using the current capture parameters, and should only be taken as an estimation. Any change in the capture properties (window size, screen depth, etc) can make this number change significantly.");
