#!/bin/sh
set -e

sample () {
  echo === $1 $2 $3 $4 ===
  if test -z "$4"; then
    ./io -x $1 -d $2 -o $1-$2.$3
  else
    ./io -x $1 -d $2 -d $3 -o $1-$2-$3.$4
  fi
}

sample mp1e_mpeg1_ps mpeg1_video mpg
sample mp1e_mpeg1_ps mpeg1_video mpeg1_audio_layer2 mpg
sample mp1e_mpeg1_ps             mpeg1_audio_layer2 mpg
sample mp1e_mpeg1_ps mpeg1_video mpeg2_audio_layer2 mpg
sample mp1e_mpeg1_ps             mpeg2_audio_layer2 mpg
sample mp1e_mpeg1_vcd mpeg1_video mpeg1_audio_layer2 mpg
sample mp1e_mpeg_video mpeg1_video mpg
sample mp1e_mpeg_audio mpeg1_audio_layer2 mp2
sample mp1e_mpeg_audio mpeg2_audio_layer2 mp2
sample ffmpeg_mpeg1_ps mpeg1_video mpeg1_audio_layer2 mpg
sample ffmpeg_real rv10_video ac3_audio rm
sample ffmpeg_asf msmpeg4v3_video mpeg1_audio_layer2 asf
sample ffmpeg_swf mjpeg_video mpeg1_audio_layer2 swf
sample ffmpeg_avi msmpeg4v3_video mpeg1_audio_layer2 avi
sample ffmpeg_mpeg_video mpeg1_video mpg
sample ffmpeg_mpeg_video h263_video mpg
sample ffmpeg_mpeg_video h263p_video mpg
sample ffmpeg_mpeg_video mpeg4_video mpg
sample ffmpeg_mpeg_video msmpeg4v1_video mpg
sample ffmpeg_mpeg_video msmpeg4v2_video mpg
sample ffmpeg_mpeg_video msmpeg4v2_video mpg
sample ffmpeg_mpeg_video mjpeg_video mjpg
sample ffmpeg_mpeg_video rv10_video rm
sample ffmpeg_riff_wave mpeg1_audio_layer2 wav
sample ffmpeg_riff_wave mpeg2_audio_layer2 wav
sample ffmpeg_riff_wave ac3_audio wav
sample ffmpeg_riff_wave pcm_s16le wav
sample ffmpeg_riff_wave pcm_u8 wav
sample ffmpeg_riff_wave pcm_alaw wav
sample ffmpeg_riff_wave pcm_mulaw wav
sample ffmpeg_mpeg_audio mpeg1_audio_layer2 mp2
sample ffmpeg_mpeg_audio mpeg2_audio_layer2 mp2
sample ffmpeg_ac3_audio ac3_audio ac3
sample ffmpeg_au_audio pcm_s16be au
